name: Update Image Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 1 UTC everyday
    - cron: "* * * * *"

jobs:
  update-readme:
    name: Update Image README
    runs-on: ubuntu-latest
    steps:
      - uses: Sceleratis/update-readme-image@main
        with:
          IMG_ALT: Woops. Guess the image failed...
          ALIGN: left;
          WIDTH: 400;
          HEIGHT: 400;
